### ISSUE TITLE
How to find out which date an opinion was created?

### ISSUE THREAD

**Issue by debsankha** [Network-Dynamics/lawevol#3]
*  Each `OpinionCluster` has a `date_filed` property
*  Each `Docket` has these date fields:
     *  `date_ argued`
     *  `date_ reargued`
     *  `date_ blocked`

My question is: out of all these, which one represents the date when an opinion was made?

**Comment by dataspider** [comment]
Assuming that by "when an opinion was made" you mean when it was "published":
the data_filed property is what we need.
Sometimes, there is a huge time lapse between the argument of the case and the publication of the decision (would be interesting to see if these cases occupy special positions in the network).

**Comment by debsankha** [comment]
Thanks @dataspider .

the `date_argued` field seems to be `null` in all cases, though. So maybe they did not manage to collect that data.
